CDAR-732: Remove redundant requests
usdot-fhwa-stol/cdasim pull request #195
Opened 2024-01-19 16:13 UTC by paulbourelly999

Remove redundant requests to XMLRPC CARLA CDA Sim adapter server

# PR Details
## Description

## Related GitHub Issue

## Related Jira Key

## Motivation and Context

## How Has This Been Tested?

## Types of changes

- [ ] Defect fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that cause existing functionality to change)

## Checklist:

- [ ] I have added any new packages to the sonar-scanner.properties file
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING**](https://github.com/usdot-fhwa-stol/carma-platform/blob/develop/Contributing.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2024-01-22 18:01 UTC, MishkaMN requested changes

2024-01-22 18:01 UTC, MishkaMN commented on co-simulation/fed/mosaic-carla/src/main/java/org/eclipse/mosaic/fed/carla/ambassador/CarlaAmbassador.java
>              // CARLA but it seems to increment every time processTimeAdvanceGrant is called
we should remove this comment now

2024-01-22 22:01 UTC, kjrush commented
Seems good to me, I'm okay with approving it just on a review, but want to confirm the testing. How long were the test cases you ran? I think we were seeing the previous livelock issue occurring at like 5ish minutes into simulation execution. To my recollection it was stochastic though, it just happened that about 5 minutes was enough timesteps that it was pretty probable to occur.

If we can confirm that's not a problem, I'm down to approve and merge.

2024-01-22 22:46 UTC, paulbourelly999 commented
> Seems good to me, I'm okay with approving it just on a review, but want to confirm the testing. How long were the test cases you ran? I think we were seeing the previous livelock issue occurring at like 5ish minutes into simulation execution. To my recollection it was stochastic though, it just happened that about 5 minutes was enough timesteps that it was pretty probable to occur.
> 
> If we can confirm that's not a problem, I'm down to approve and merge.

Hey @kjrush out test case is significantly shorted than 5 minutes. Regardless if this bug is there are not after 5 minutes, this is definitely not the fix and seems to at least partially negatively impact performance. I will try to run a 10 minute simulation and see what happens

2024-01-22 22:48 UTC, paulbourelly999 commented on co-simulation/fed/mosaic-carla/src/main/java/org/eclipse/mosaic/fed/carla/ambassador/CarlaAmbassador.java
>              // CARLA but it seems to increment every time processTimeAdvanceGrant is called
addressed

2024-01-23 01:21 UTC, MishkaMN approved these changes

2024-01-23 17:43 UTC, paulbourelly999 commented
> > Seems good to me, I'm okay with approving it just on a review, but want to confirm the testing. How long were the test cases you ran? I think we were seeing the previous livelock issue occurring at like 5ish minutes into simulation execution. To my recollection it was stochastic though, it just happened that about 5 minutes was enough timesteps that it was pretty probable to occur.
> > If we can confirm that's not a problem, I'm down to approve and merge.
> 
> Hey @kjrush out test case is significantly shorted than 5 minutes. Regardless if this bug is there are not after 5 minutes, this is definitely not the fix and seems to at least partially negatively impact performance. I will try to run a 10 minute simulation and see what happens

@kjrush Tested for 5 minute simulation, other services crashed but no CDASim

2024-01-23 17:49 UTC, MishkaMN approved these changes

2024-01-23 20:26 UTC, MishkaMN approved these changes

2024-01-23 22:59 UTC, paulbourelly999 commented
I am going to merge this and independently see I the issues with RTI event priority dead lock can be recreated. It is possible this change re introduces this behavior but with VRU UC simulation scenarios this behavior seems to not be present. Might be more likely with the addition of SUMO actors. The fix that is undone by this PR is likely not the long term fix. If this PR re introduces the bug we can make a decision independently about whether to find a more long term fix or revert to this fix

2024-01-23 22:59 UTC, merged